--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(1,1,NULL,'G');
    
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(2,2,NULL,'G');
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(3,3,NULL,'KG');
--
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(4,4,NULL,'KG');

--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(5,NULL,1,'G');
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(6,NULL,2,'EA');
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(7,NULL,3,'EA');
--INSERT INTO PRODUCT(PRO_NUM,FRUIT_NUM,VEG_NUM,AMOUNT)
--    VALUES(8,NULL,4,'G');


SELECT * FROM PRODUCT;