--INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
--    VALUES(1,'상추',1000);
--
--INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
--    VALUES(2,'배추',2000);
--
--
--INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
--    VALUES(3,'시금치',1500);
--    
--INSERT INTO VEGETABLE(VEG_NUM,VEG_NAME,VEG_PRICE)
--    VALUES(4,'방울토마토',3000);




--
--INSERT INTO FRUIT(FRUIT_NUM, FRUIT_NAME, FRUIT_PRICE)
--    VALUES(1,'사과',3000);
--
--INSERT INTO FRUIT(FRUIT_NUM, FRUIT_NAME, FRUIT_PRICE)
--    VALUES(2,'귤',1000);
--    
--INSERT INTO FRUIT(FRUIT_NUM, FRUIT_NAME, FRUIT_PRICE)
--    VALUES(3,'딸기',8000);
--    
--INSERT INTO FRUIT(FRUIT_NUM, FRUIT_NAME, FRUIT_PRICE)
--    VALUES(4,'수박',20000);


--
--INSERT INTO WEIGHT(AMOUNT)
--    VALUES('EA');
--INSERT INTO WEIGHT(AMOUNT)
--    VALUES('G');
--INSERT INTO WEIGHT(AMOUNT)
--    VALUES('KG');